Some Typo fixes.
plfa/plfa.github.io pull request #558
Opened 2021-02-11 16:23 UTC by capn-freako

These are just some typo fixes I made, while making my way through the end of Part 2 and the _Denotational_ chapter.

2021-02-11 18:34 UTC, wadler requested changes
This hint is out of date. I've already updated the text with an improved hint, based on discussion with David.

2021-02-11 18:35 UTC, wadler requested changes
See comment on previous change.

2021-02-11 18:36 UTC, wadler requested changes
See previous comment.

2021-02-11 18:37 UTC, wadler requested changes
See previous comment.

2021-02-11 18:37 UTC, wadler reviewed
Jeremy needs to review these.

2021-02-11 18:40 UTC, wadler commented
Most of these changes are to the dagger exercise in Bisimulation, which I already fixed after a discussion with David, so they are out of date. They should be deleted from the request. The other changes are to denotational and should not be bundled with these; they need to be approved by Jeremy, the principal author of that chapter.

2021-02-11 18:42 UTC, jsiek commented
I’ll take a look after the un-bundling.

Cheers,
Jeremy

> On Feb 11, 2021, at 1:41 PM, Philip Wadler <notifications@github.com> wrote:
> 
> 
> Most of these changes are to the dagger exercise in Bisimulation, which I already fixed after a discussion with David, so they are out of date. They should be deleted from the request. The other changes are to denotational and should not be bundled with these; they need to be approved by Jeremy, the principal author of that chapter.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <https://github.com/plfa/plfa.github.io/pull/558#issuecomment-777704783>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA5IGPAXLQ6M5E6UP7SVEZ3S6QQD3ANCNFSM4XPD6SFQ>.
>

2021-02-14 15:14 UTC, capn-freako commented
Please pardon my nascent Git-fu here, but I:

1. Can't seem to link any of your comments to a particular change.
2. Don't see any changes to _Bisimulation_ in the pull request. (I see two files changed: _Inference_ and _Denotational_.)
3. Am not sure how to split this pull request, now that it's been submitted.

Thanks,
-db

2021-02-14 22:10 UTC, jsiek commented
The suggested changes to the Denotational chapter look good.

2021-02-24 01:47 UTC, jsiek commented on src/plfa/part2/Inference.lagda.md
> +      M⁻ ↓ A                              switch to synthesized
It looks to me like "switch to inherited" was correct, so no change needed.

2021-02-24 01:48 UTC, jsiek commented on src/plfa/part2/Inference.lagda.md
> +      M⁺ ↑                                switch to inherited
It looks to me like "switch to synthesized" was correct, so no change needed.

2021-02-24 04:23 UTC, capn-freako commented
But, isn't that inconsistent with both the text above:

Hence, we need a way to treat a synthesized term as if it is inherited. We
> introduce a new term form, M ↑ for this purpose.


and the definition:

  _↓_ <https://plfa.github.io/Inference/#12229>
: Term⁻ <https://plfa.github.io/Inference/#12104> → Type
<https://plfa.github.io/Inference/#11725> → Term⁺
<https://plfa.github.io/Inference/#12087>


?

On Tue, Feb 23, 2021 at 5:48 PM Jeremy G. Siek <notifications@github.com>
wrote:

> *@jsiek* commented on this pull request.
> ------------------------------
>
> In src/plfa/part2/Inference.lagda.md
> <https://github.com/plfa/plfa.github.io/pull/558#discussion_r581545626>:
>
> > @@ -188,15 +188,15 @@ We can extract the grammar for terms from the above:
>
>      L⁺, M⁺, N⁺ ::=                      terms with synthesized type
>
>        x                                   variable
>
>        L⁺ · M⁻                             application
>
> -      M⁻ ↓ A                              switch to inherited
>
> +      M⁻ ↓ A                              switch to synthesized
>
>
> It looks to me like "switch to inherited" was correct, so no change needed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/plfa/plfa.github.io/pull/558#pullrequestreview-596989927>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH7XGTJ3QBZOJXF4EQMBJ3TARLFDANCNFSM4XPD6SFQ>
> .
>

2021-02-24 14:05 UTC, jsiek commented
My understanding is that the text above is written from the perspective
of going from inside to out… you’ve got a synthesized term M
and want to use it in a context that in inherited, so you write M ↑.

The grammar comments are written from the perspective of
going from outside to inside. If you’re in an inherited context
and want to fill it in with a synthesized term M, you write M ↑.

Perhaps the best fix is to adjust the grammar comments or the text
to take the same perspective.

Cheers,
Jeremy


> On Feb 23, 2021, at 11:23 PM, David Banas <notifications@github.com> wrote:
> 
> 
> But, isn't that inconsistent with both the text above:
> 
> Hence, we need a way to treat a synthesized term as if it is inherited. We
> > introduce a new term form, M ↑ for this purpose.
> 
> 
> and the definition:
> 
> _↓_ <https://plfa.github.io/Inference/#12229>
> : Term⁻ <https://plfa.github.io/Inference/#12104> → Type
> <https://plfa.github.io/Inference/#11725> → Term⁺
> <https://plfa.github.io/Inference/#12087>
> 
> 
> ?
> 
> On Tue, Feb 23, 2021 at 5:48 PM Jeremy G. Siek <notifications@github.com>
> wrote:
> 
> > *@jsiek* commented on this pull request.
> > ------------------------------
> >
> > In src/plfa/part2/Inference.lagda.md
> > <https://github.com/plfa/plfa.github.io/pull/558#discussion_r581545626>:
> >
> > > @@ -188,15 +188,15 @@ We can extract the grammar for terms from the above:
> >
> > L⁺, M⁺, N⁺ ::= terms with synthesized type
> >
> > x variable
> >
> > L⁺ · M⁻ application
> >
> > - M⁻ ↓ A switch to inherited
> >
> > + M⁻ ↓ A switch to synthesized
> >
> >
> > It looks to me like "switch to inherited" was correct, so no change needed.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/plfa/plfa.github.io/pull/558#pullrequestreview-596989927>,
> > or unsubscribe
> > <https://github.com/notifications/unsubscribe-auth/AAH7XGTJ3QBZOJXF4EQMBJ3TARLFDANCNFSM4XPD6SFQ>
> > .
> >
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub <https://github.com/plfa/plfa.github.io/pull/558#issuecomment-784747046>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA5IGPDRY6OTZODMY35CS5TTAR5LTANCNFSM4XPD6SFQ>.
>

2021-02-24 16:02 UTC, capn-freako commented
Okay, but in either case below, the expression: M ↑, is taking a synthesized term and making it an inherited term; correct?

I think the comments in the code currently have that reversed.

-db


> On Feb 24, 2021, at 6:06 AM, Jeremy G. Siek <notifications@github.com> wrote:
> 
> 
> My understanding is that the text above is written from the perspective
> of going from inside to out… you’ve got a synthesized term M
> and want to use it in a context that in inherited, so you write M ↑.
> 
> The grammar comments are written from the perspective of
> going from outside to inside. If you’re in an inherited context
> and want to fill it in with a synthesized term M, you write M ↑.
> 
> Perhaps the best fix is to adjust the grammar comments or the text
> to take the same perspective.
> 
> Cheers,
> Jeremy
> 
> 
> > On Feb 23, 2021, at 11:23 PM, David Banas <notifications@github.com> wrote:
> > 
> > 
> > But, isn't that inconsistent with both the text above:
> > 
> > Hence, we need a way to treat a synthesized term as if it is inherited. We
> > > introduce a new term form, M ↑ for this purpose.
> > 
> > 
> > and the definition:
> > 
> > _↓_ <https://plfa.github.io/Inference/#12229>
> > : Term⁻ <https://plfa.github.io/Inference/#12104> → Type
> > <https://plfa.github.io/Inference/#11725> → Term⁺
> > <https://plfa.github.io/Inference/#12087>
> > 
> > 
> > ?
> > 
> > On Tue, Feb 23, 2021 at 5:48 PM Jeremy G. Siek <notifications@github.com>
> > wrote:
> > 
> > > *@jsiek* commented on this pull request.
> > > ------------------------------
> > >
> > > In src/plfa/part2/Inference.lagda.md
> > > <https://github.com/plfa/plfa.github.io/pull/558#discussion_r581545626>:
> > >
> > > > @@ -188,15 +188,15 @@ We can extract the grammar for terms from the above:
> > >
> > > L⁺, M⁺, N⁺ ::= terms with synthesized type
> > >
> > > x variable
> > >
> > > L⁺ · M⁻ application
> > >
> > > - M⁻ ↓ A switch to inherited
> > >
> > > + M⁻ ↓ A switch to synthesized
> > >
> > >
> > > It looks to me like "switch to inherited" was correct, so no change needed.
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/plfa/plfa.github.io/pull/558#pullrequestreview-596989927>,
> > > or unsubscribe
> > > <https://github.com/notifications/unsubscribe-auth/AAH7XGTJ3QBZOJXF4EQMBJ3TARLFDANCNFSM4XPD6SFQ>
> > > .
> > >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub <https://github.com/plfa/plfa.github.io/pull/558#issuecomment-784747046>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA5IGPDRY6OTZODMY35CS5TTAR5LTANCNFSM4XPD6SFQ>.
> > 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/plfa/plfa.github.io/pull/558#issuecomment-785098943>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAH7XGSA6P5HCC2OPGWKACLTAUBUZANCNFSM4XPD6SFQ>.
>

2021-02-24 16:09 UTC, jsiek commented
> On Feb 24, 2021, at 11:03 AM, David Banas <notifications@github.com> wrote:
> 
> 
> Okay, but in either case below, the expression: M ↑, is taking a synthesized term and making it an inherited term; correct?
> 

Yes

> I think the comments in the code currently have that reversed.
> 

What I was trying to say below is that the comment

"switch to synthesized"

should be interpreted to mean

“switch from an inherited context to a synthesized context”

and not

“switch an inherited term into a synthesized term”

Cheers,
Jeremy


> -db
> 
> 
> > On Feb 24, 2021, at 6:06 AM, Jeremy G. Siek <notifications@github.com> wrote:
> > 
> > 
> > My understanding is that the text above is written from the perspective
> > of going from inside to out… you’ve got a synthesized term M
> > and want to use it in a context that in inherited, so you write M ↑.
> > 
> > The grammar comments are written from the perspective of
> > going from outside to inside. If you’re in an inherited context
> > and want to fill it in with a synthesized term M, you write M ↑.
> > 
> > Perhaps the best fix is to adjust the grammar comments or the text
> > to take the same perspective.
> > 
> > Cheers,
> > Jeremy
> > 
> > 
> > > On Feb 23, 2021, at 11:23 PM, David Banas <notifications@github.com> wrote:
> > > 
> > > 
> > > But, isn't that inconsistent with both the text above:
> > > 
> > > Hence, we need a way to treat a synthesized term as if it is inherited. We
> > > > introduce a new term form, M ↑ for this purpose.
> > > 
> > > 
> > > and the definition:
> > > 
> > > _↓_ <https://plfa.github.io/Inference/#12229>
> > > : Term⁻ <https://plfa.github.io/Inference/#12104> → Type
> > > <https://plfa.github.io/Inference/#11725> → Term⁺
> > > <https://plfa.github.io/Inference/#12087>
> > > 
> > > 
> > > ?
> > > 
> > > On Tue, Feb 23, 2021 at 5:48 PM Jeremy G. Siek <notifications@github.com>
> > > wrote:
> > > 
> > > > *@jsiek* commented on this pull request.
> > > > ------------------------------
> > > >
> > > > In src/plfa/part2/Inference.lagda.md
> > > > <https://github.com/plfa/plfa.github.io/pull/558#discussion_r581545626>:
> > > >
> > > > > @@ -188,15 +188,15 @@ We can extract the grammar for terms from the above:
> > > >
> > > > L⁺, M⁺, N⁺ ::= terms with synthesized type
> > > >
> > > > x variable
> > > >
> > > > L⁺ · M⁻ application
> > > >
> > > > - M⁻ ↓ A switch to inherited
> > > >
> > > > + M⁻ ↓ A switch to synthesized
> > > >
> > > >
> > > > It looks to me like "switch to inherited" was correct, so no change needed.
> > > >
> > > > —
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly, view it on GitHub
> > > > <https://github.com/plfa/plfa.github.io/pull/558#pullrequestreview-596989927>,
> > > > or unsubscribe
> > > > <https://github.com/notifications/unsubscribe-auth/AAH7XGTJ3QBZOJXF4EQMBJ3TARLFDANCNFSM4XPD6SFQ>
> > > > .
> > > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly, view it on GitHub <https://github.com/plfa/plfa.github.io/pull/558#issuecomment-784747046>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA5IGPDRY6OTZODMY35CS5TTAR5LTANCNFSM4XPD6SFQ>.
> > > 
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub <https://github.com/plfa/plfa.github.io/pull/558#issuecomment-785098943>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAH7XGSA6P5HCC2OPGWKACLTAUBUZANCNFSM4XPD6SFQ>.
> > 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub <https://github.com/plfa/plfa.github.io/pull/558#issuecomment-785181634>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA5IGPGKUGFGIBY6PZVLMXDTAUPLPANCNFSM4XPD6SFQ>.
>

2022-06-18 18:27 UTC, wenkokke commented
Closed due to inactivity.

Perhaps submitting some of these changes as separate PRs would make it easier to merge them quickly.

2022-06-18 18:27 UTC, closed without merging