Michael's update
plfa/plfa.github.io pull request #865
Opened 2023-05-16 18:18 UTC by wadler

Improved description of exercises in Preface, plus a few related changes. Suggested by Michael PJ.

2023-05-16 22:04 UTC, wenkokke requested changes
Please don't merge this

2023-05-16 22:04 UTC, wenkokke commented on README.md
> -[![pre-commit.ci status][pre-commit-status-svg]][pre-commit-status-url]
Why did you remove this badge?

2023-05-16 22:04 UTC, wenkokke commented on README.md
> +### Atom
You seem to have added this section back in, but Atom is deprecated.

2023-05-16 22:04 UTC, wenkokke commented on README.md
> -[plfa-badge-status-svg]: https://github.com/plfa/plfa.github.io/actions/workflows/build.yml/badge.svg
These changes also undo previous changes.

2023-05-16 22:04 UTC, wenkokke commented on README.md
> -[agda-readthedocs-installation]: https://agda.readthedocs.io/en/v2.6.3/getting-started/installation.html
These undo previous changes.

2023-05-17 08:08 UTC, wadler commented
Thanks. Good catch. I didn't go through the proper git steps the first time I made changes, and when I replayed the changes I inadvertently reverted some files. I've submitted a second pull request (tspl-update-michael-2) which I believe is now correct.

When I came in this morning, the checks on tspl-update-michael (the original) had not yet completed though they were running all night. That's a long time for checks! How long is it until they time out?

2023-05-17 13:16 UTC, closed without merging